version: "3.8"

services:
    website:
        image: caddy-builder:latest
        container_name: main
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - dokploy-network

networks:
    dokploy-network:
        external: true
