version: "3.8"

services:
    website:
        image: caddy-builder:latest
        container_name: main
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - dokploy-network
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.myapi.rule=Host(`northnet-software.ru`)"
          - "traefik.http.routers.myapi.entrypoints=websecure"
          - "traefik.http.services.myapi.loadbalancer.server.port=80"

networks:
    dokploy-network:
        external: true
